services:
  - type: web
    name: duqanvision-api
    env: python
    pythonVersion: "3.11.0"
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn rag_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."
      - key: PIP_USE_PEP517
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: MODEL_NAME
        value: gpt-3.5-turbo
      - key: MODEL_TEMPERATURE
        value: 0.7
      - key: MODEL_MAX_TOKENS
        value: 1000
      - key: VECTOR_TABLE
        value: documents
      - key: VECTOR_QUERY_FN
        value: match_documents
